#!/bin/bash

UMASK=0077
PATH=/bin:/usr/bin

# TODO Add checks for wget, etc. ?
# FIXME Assumes users shell is bash
# FIXME Does not take into account a user-local Perl 

local_lib_version=$(wget -q -O - http://cpanmetadb.appspot.com/v1.0/package/local::lib | awk '$1=="distfile:"{ print $2 }')
[[ $local_lib_version = *.tar.gz ]] || { echo 'FATAL: Unable to detect latest version of local::lib' >&2; exit 1; }

cpanm='http://xrl.us/cpanm'
local_lib="http://search.cpan.org/CPAN/authors/id/$local_lib_version"
twircer='http://github.com/crazy4swayze/twircer/raw/master/twircer'

tarball_name="${local_lib_version##*/}"
workdir="${tarball_name%.tar.gz}"

echo 'Installing local-lib ...'
wget -q "$local_lib" || { echo 'FATAL: Unable to fetch local-lib sources.' >&2; exit 1; }

tar xzf "$tarball_name"
cd "$workdir" || { echo 'FATAL: cd failed.' >&2; exit 1; }
yes | perl Makefile.PL --bootstrap --no-manpages &> /dev/null
{ make test && make install; } &>/dev/null || { echo 'FATAL: Unable to install local-lib.' >&2; exit 1; }

# Setup local::lib
echo 'eval $(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)' >>~/.bashrc

cd .. || { echo 'FATAL: cd failed.' >&2; exit 1; }
rm -rf "$workdir/" "$tarball_name"

# TODO source bashrc to read local::lib's variables
# Is there a better way to do this?
source ~/.bashrc

mkdir -p ~/bin
cd ~/bin || { echo 'FATAL: cd failed.' >&2; exit 1; }

echo 'Installing cpanm ...'
wget -q "$cpanm" || { echo 'FATAL: Unable to fetch cpanm sources.' >&2; exit 1; }
chmod +x cpanm
# TODO check if modules installed correctly?
./cpanm -n YAML::Tiny LWP::UserAgent::POE Net::Twitter::Lite POE::Component::IRC::State

echo
echo '---'
echo 'Installing twircer ...'
wget -q "$twircer" || { echo 'FATAL: Unable to fetch twircer sources.' >&2; exit 1; }
chmod +x twircer

mkdir ~/.twircer &>/dev/null || { echo 'FATAL: Unable to create ~/.twircer/' >&2; exit 1; }
cat > ~/.twircer/config <<EOF
# example configuration MUST BE EDITED!!!!!!
# nick: doejuffy
# channels:
#     - #redbrick
#     - #someotherchannel
# server: irc.redbrick.dcu.ie
# username: doejuffy
# password: secret
# trigger: JOE
edited: crazy4swayze # Remove this line after you've configured this file.
EOF

echo 'CONGRATZ! Somehow it worked ...'
echo 'Edit ~/.twircer/config then run ~/bin/twircer'
